// This file is auto-generated by @hey-api/openapi-ts

export const AIRequestSchema = {
    properties: {
        prompt: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Prompt',
            description: 'The user prompt'
        }
    },
    type: 'object',
    required: [
        'prompt'
    ],
    title: 'AIRequest'
} as const;

export const AIResponseSchema = {
    properties: {
        answer: {
            type: 'string',
            minLength: 1,
            title: 'Answer',
            description: 'The generated answer'
        },
        confidence: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Confidence',
            description: 'Confidence score 0-1'
        },
        sources: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Sources',
            description: 'Referenced sources if any'
        }
    },
    type: 'object',
    required: [
        'answer',
        'confidence'
    ],
    title: 'AIResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
