// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AiGenerateTextData, AiGenerateTextErrors, AiGenerateTextResponses, UtilsHealthCheckData, UtilsHealthCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new OneAdvisorService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class OneAdvisorService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<OneAdvisorService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        OneAdvisorService.__registry.set(this, args?.key);
    }
    
    /**
     * Health Check
     */
    public operation<ThrowOnError extends boolean = false>(options?: Options<UtilsHealthCheckData, ThrowOnError>) {
        return (options?.client ?? this.client).get<UtilsHealthCheckResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/utils/health-check/',
            ...options
        });
    }
    
    /**
     * Generate Text
     *
     * Generate a structured AI response using xAI Grok with tool support.
     */
    public operation2<ThrowOnError extends boolean = false>(options: Options<AiGenerateTextData, ThrowOnError>) {
        return (options.client ?? this.client).post<AiGenerateTextResponses, AiGenerateTextErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/ai/generate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
